[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
lib_deps =
    miguelbalboa/MFRC522@^1.4.10
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.9
    adafruit/Adafruit SPIFlash
    adafruit/Adafruit BusIO